"""Mirrors apps/api/src/risk/dto/risk-event-input.dto.ts and
apps/api/src/risk/risk.service.ts's RiskDecisionResponse. Kept in sync manually — see the
Node SDK's README for why this isn't yet generated from the OpenAPI spec (a documented
Phase 7 gap, not hidden).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Optional

RiskEventType = Literal["LOGIN", "SESSION_START", "PAYMENT", "SUBSCRIPTION_REGION_CHANGE"]


@dataclass(frozen=True)
class RiskEventInput:
    account_id: str
    """Tenant's own opaque identifier for the end account."""
    sdk_session_id: str
    """SDK's own session correlation id (opaque string, generated by the caller)."""
    ip_address: str
    device_id: str
    """SDK-generated device identifier — must NOT be a hardware serial number."""
    timestamp: str
    """ISO 8601 timestamp of the event."""
    pricing_country: str
    """ISO 3166-1 alpha-2 country code of the billed/pricing region."""
    event_type: RiskEventType
    timezone: Optional[str] = None
    locale: Optional[str] = None
    payment_country: Optional[str] = None
    """Derived from a tokenized payment signal — never a raw card number."""

    def to_api_dict(self) -> Dict[str, Any]:
        """Serializes to the exact camelCase JSON shape RiskEventInputDto expects."""
        payload: Dict[str, Any] = {
            "accountId": self.account_id,
            "sdkSessionId": self.sdk_session_id,
            "ipAddress": self.ip_address,
            "deviceId": self.device_id,
            "timestamp": self.timestamp,
            "pricingCountry": self.pricing_country,
            "eventType": self.event_type,
        }
        if self.timezone is not None:
            payload["timezone"] = self.timezone
        if self.locale is not None:
            payload["locale"] = self.locale
        if self.payment_country is not None:
            payload["paymentCountry"] = self.payment_country
        return payload


@dataclass(frozen=True)
class RiskDecision:
    risk_score: float
    confidence: str
    likely_primary_country: Dict[str, float]
    vpn_probability: float
    travel_probability: float
    policy_action: str
    requires_human_review: bool
    reason_codes: List[str] = field(default_factory=list)
    model_version: str = ""
    policy_version: str = ""
    investigation_id: Optional[str] = None

    @staticmethod
    def from_api_dict(data: Dict[str, Any]) -> "RiskDecision":
        return RiskDecision(
            risk_score=data["riskScore"],
            confidence=data["confidence"],
            likely_primary_country=data.get("likelyPrimaryCountry", {}),
            vpn_probability=data["vpnProbability"],
            travel_probability=data["travelProbability"],
            policy_action=data["policyAction"],
            requires_human_review=data["requiresHumanReview"],
            reason_codes=data.get("reasonCodes", []),
            model_version=data.get("modelVersion", ""),
            policy_version=data.get("policyVersion", ""),
            investigation_id=data.get("investigationId"),
        )
