/**
 * Mirrors apps/api/src/risk/dto/risk-event-input.dto.ts and
 * apps/api/src/risk/risk.service.ts's RiskDecisionResponse. Kept in sync manually — see
 * README.md "Keeping this SDK in sync with the API" for why this isn't yet generated from
 * the OpenAPI spec (a documented Phase 7 gap, not hidden).
 */
export type RiskEventType = 'LOGIN' | 'SESSION_START' | 'PAYMENT' | 'SUBSCRIPTION_REGION_CHANGE';

export interface RiskEventInput {
  /** Tenant's own opaque identifier for the end account. */
  accountId: string;
  /** SDK's own session correlation id (opaque string, generated by the caller). */
  sdkSessionId: string;
  ipAddress: string;
  /** SDK-generated device identifier — must NOT be a hardware serial number. */
  deviceId: string;
  /** ISO 8601 timestamp of the event. */
  timestamp: string;
  /** ISO 3166-1 alpha-2 country code of the billed/pricing region. */
  pricingCountry: string;
  timezone?: string;
  locale?: string;
  /** Derived from a tokenized payment signal — never a raw card number. */
  paymentCountry?: string;
  eventType: RiskEventType;
}

export interface RiskDecision {
  riskScore: number;
  confidence: string;
  likelyPrimaryCountry: Record<string, number>;
  vpnProbability: number;
  travelProbability: number;
  policyAction: string;
  requiresHumanReview: boolean;
  reasonCodes: string[];
  modelVersion: string;
  policyVersion: string;
  investigationId: string | null;
}

export interface PriceGuardClientOptions {
  /** Base URL of the PriceGuard API, e.g. "https://api.priceguard.example" or a local instance. */
  baseUrl: string;
  /** Full API key, e.g. "gg_live_abcdef.somesecret" (prefix + secret, dot-joined — see ApiKeyGuard). */
  apiKey: string;
  /** Per-request timeout in milliseconds. Defaults to 10_000. */
  timeoutMs?: number;
  /** Override fetch (mainly for tests); defaults to the global fetch. */
  fetchImpl?: typeof fetch;
}
